### ISSUE TITLE
[HttpError]: Empty value for parameter 'deployment_id': undefined

### ISSUE THREAD

**Issue by typeofweb** [patrickedqvist/wait-for-vercel-preview#1]
Link to the build: https://github.com/typeofweb/devfaq-www/runs/728980415

```
Run patrickedqvist/wait-for-vercel-preview@v1.0.3
  with:
    token: ***
    max_timeout: 60
RequestError [HttpError]: Empty value for parameter 'deployment_id': undefined
    at /home/runner/work/_actions/patrickedqvist/wait-for-vercel-preview/v1.0.3/node_modules/@octokit/rest/plugins/validate/validate.js:74:15
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/patrickedqvist/wait-for-vercel-preview/v1.0.3/node_modules/@octokit/rest/plugins/validate/validate.js:42:12
    at Array.forEach (<anonymous>)
    at validate (/home/runner/work/_actions/patrickedqvist/wait-for-vercel-preview/v1.0.3/node_modules/@octokit/rest/plugins/validate/validate.js:15:23) {
  name: 'HttpError',
  status: 400,
  headers: {},
  request: {
    method: 'GET',
    baseUrl: 'https://api.github.com',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.3; x64)'
    },
    mediaType: { format: '', previews: [] },
    request: { hook: [Function: bound bound register], validate: [Object] },
    url: '/repos/:owner/:repo/deployments/:deployment_id/statuses/:status_id',
    owner: undefined,
    repo: undefined,
    deployment_id: undefined,
    status_id: undefined
  }
}
```

**Comment by klapec** [comment]
Happened to me as well. I can't share the build logs but it's been fine for the first couple of runs within the same PR - it stopped working after ~5th commit or so.

**Comment by patrickedqvist** [comment]
Could you try running with `patrickedqvist/wait-for-vercel-preview@master` instead of `v1.0.3` and see if that resolves the issue?

**Comment by klapec** [comment]
@patrickedqvist it seems to have worked for the first new commit but now it hangs on `Deployment unavailable or not successful, retrying...`, even though both Vercel and Github report that the branch has been successfully deployed. Could you log the caught error here https://github.com/patrickedqvist/wait-for-vercel-preview/blob/master/index.js#L45?

**Comment by klapec** [comment]
Second try - it seems to have worked now, not sure what happened before.

**Comment by patrickedqvist** [comment]
I've updated the master branch with some more error logs. Open a new issue if you come across more trouble :)
