### ISSUE TITLE
Delete or update releases

### ISSUE THREAD

**Issue by connorads** [patrickedqvist/wait-for-vercel-preview#2]
Hey @patrickedqvist, thanks for making this, it works gr888!

I made a mistake whilst using it though.

I wanted to use a fixed version in my pipeline, so I went to the release page and took the latest release.
https://github.com/patrickedqvist/wait-for-vercel-preview/releases
![image](https://user-images.githubusercontent.com/10026538/85065963-f5378c80-b1a5-11ea-9860-dbf736ba3106.png)
`patrickedqvist/wait-for-vercel-preview@v1.0.3`
But that version doesn't work!
![image](https://user-images.githubusercontent.com/10026538/85066219-6d05b700-b1a6-11ea-873f-7464562873b5.png)

Now I'm just using the latest commit hash
`patrickedqvist/wait-for-vercel-preview@4b65b42`

I was being a bit silly but maybe it's worth deleting all the releases if they're not going to be maintained/automated?

**Comment by patrickedqvist** [comment]
Releases updated, thank you :)
