### ISSUE TITLE
This Action cannot be found in GitHub Marketplace

### ISSUE THREAD

**Issue by TonyRL** [patrickedqvist/wait-for-vercel-preview#29]
I tried both "Vercel" and "wait-for-vercel-preview" but neither https://github.com/search?q=vercel&type=marketplace nor https://github.com/marketplace?query=vercel return this action from the results

**Comment by patrickedqvist** [comment]
Hello @TonyRL 

This has been intentional for some time. The action has been in a period of maturing and thus only been available through the Github registry. However, the latest release should now be available in the marketplace 🎉
