### ISSUE TITLE
Create New Release?

### ISSUE THREAD

**Issue by pip8786** [patrickedqvist/wait-for-vercel-preview#50]
It appears the latest release was back in Feb 2022, but there's been quite a few PRs merged since then. Could you create a new release? Is there a way to use the latest in our actions without a new release?

**Comment by patrickedqvist** [comment]
You can specify a branch rather then a specific version :)

**Comment by checkerschaf** [comment]
@patrickedqvist This could break the CI at any time. I think it would be nice to pin it to a version :)

**Comment by patrickedqvist** [comment]
Thanks for your input @checkerschaf 💯  I've released a v1.3.0

**Comment by checkerschaf** [comment]
@patrickedqvist You're welcome. Thanks for creating a new release so fast 🥳

**Comment by brunolucena** [comment]
@patrickedqvist after updating to v1.3.0 the package is failing

`Download action repository 'patrickedqvist/wait-for-vercel-preview@v1.3.0' (SHA:ee6b0d1d63a92fa814d742cc997a9ced0b8d565f)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load patrickedqvist/wait-for-vercel-preview/v1.3.0/action.yml`

It looks like this recent change, updating from node16 to node18 may be the cause? https://github.com/patrickedqvist/wait-for-vercel-preview/pull/51/files
