### ISSUE TITLE
After updating to v1.3.0 the package is failing

### ISSUE THREAD

**Issue by brunolucena** [patrickedqvist/wait-for-vercel-preview#52]
After updating to v1.3.0 the package is failing

`Download action repository 'patrickedqvist/wait-for-vercel-preview@v1.3.0' (SHA:ee6b0d1d63a92fa814d742cc997a9ced0b8d565f)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load patrickedqvist/wait-for-vercel-preview/v1.3.0/action.yml`

It looks like this recent change, updating from node16 to node18 may be the cause? https://github.com/patrickedqvist/wait-for-vercel-preview/pull/51/files

_Originally posted by @brunolucena in https://github.com/patrickedqvist/wait-for-vercel-preview/issues/50#issuecomment-1403760235_

**Comment by patrickedqvist** [comment]
Thanks for submitting the issue @brunolucena , I've released a v.1.3.1 with a fix

**Comment by checkerschaf** [comment]
@patrickedqvist Not sure if it was intended to add a dot in front of the version number 🤔 
You released `v.1.3.1` instead of `v1.3.1`. 😅
