### ISSUE TITLE
401 issue after updating to 1.3.0

### ISSUE THREAD

**Issue by aarsenovski** [patrickedqvist/wait-for-vercel-preview#54]
Hey everyone,

we've used v1.2.0 without any problems so far. After updating to 1.3.1 we see that runs do get the target url but then show an error with GET status: 401.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/106732697/216005126-3fa149f9-159f-4dff-a26f-799c60a966b0.png">

Will appreciate any help on resolving this issue.

**Comment by tabuchid** [comment]
@aarsenovski What fixed your issue. I'm setting this up for the first time and am seeing 401.
