### ISSUE TITLE
What happens if I have more than 1 deployment on the same repo?

### ISSUE THREAD

**Issue by felippepuhle** [patrickedqvist/wait-for-vercel-preview#7]
For example, currently, I have the app itself and our storybook.

I tested a bit and it seems to use always the app preview URL, but I'm not sure if I can trust on that premise.

Is there a way I can guarantee that? This action would simplify a lot my workflow, it seems so great.

**Comment by felippepuhle** [comment]
It just happened: 

![Screen Shot 2021-01-04 at 10 02 25 AM](https://user-images.githubusercontent.com/15961929/103537893-fbf0cd00-4e73-11eb-9e9f-b189d7403f08.png)

Storybook was deployed first so it broke everything... can we create some kind of config to ensure that we're getting the correct deployment item? not sure which property from `ReposListDeploymentStatusesResponseItem` we should compare

**Comment by patrickedqvist** [comment]
Hello @felippepuhle,

Interesting, I haven't tried this myself. At the moment I'm afraid I don't have a lot of time on my hands (buried in client work) but make a fork and see if you can implement it yourself. Contributions are more than welcome. 

My initial thoughts are that you need some information that is consistent with the deployment item so you can target for e.g storybook directly. I'm unaware of something as such exists from the Status Response Item. If there is it could be just adding a config array that you can filter those items against.

**Comment by felippepuhle** [comment]
@patrickedqvist how can I debug it? can you help adding some explanation on the README so I can take a look?
